### ISSUE TITLE
svcinfo lshostvdiskmap fails if device name starts with ls

### ISSUE THREAD

**Issue by tigerphoenixdragon** [ansible-collections/ibm.spectrum_virtualize#43] opened 2021-08-11 14:52 UTC
##### SUMMARY

We have an ansible playbook we are trying to use for taking flash copies for a system.  We use the name of the system in the flash copy name as part of our naming scheme, so when looking up which subsystem owns a server, we use "svcinfo lshostvdiskmap <hostname>" to see if it's on this subsystem so we can identify which subsystem to request the flash copy on.

Our naming scheme for our servers has some of our servers starting with an "ls" in the name.  The error we see when we try to run this module is "CMMVC5737E The parameter [-json] has been entered multiple times.  Enter the parameter only one time."

A check of the log created by the log_path directive indicates that it is indeed passing "-json" on the end after it already passed it in front of the server name such as below:
ibm_svcinfo_command.py:send_svcinfo_command():202 Executing CLI command: svcinfo lshostvdiskmap -json lsone -json

A check of the module code for ibm_svcinfo_command.py shows the following code is the likely issue:
def modify_command(self, argument):
    return ' '.join([c.strip() if not c.startswith('ls') else c + " -json" for c in argument.strip().split()])

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module ibm_svcinfo_command.py

##### ANSIBLE VERSION

```paste below
ansible 2.9.13
   config file = /etc/ansible/ansible.cfg
   configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /usr/lib/python3.6/site-packages/ansible
   executable location = /usr/bin/ansible
   python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
```

##### COLLECTION VERSION

```paste below
1.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Red Hat 8 on x86_64

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Shilpi-J** [comment] 2021-08-12 07:08
Thanks, will look into the issue.

**Comment by tigerphoenixdragon** [comment] 2021-09-15 19:06
Just curious if any progress has been made on this.

**Comment by rohitk-github** [comment] 2021-09-16 13:41
Hi. Yes expect the fix in our upcoming release. Thanks.

**Comment by Shilpi-J** [comment] 2021-09-24 05:44
The issue is fixed in IBM Spectrum Virtualize Ansible collection v1.6.0

**Comment by Shilpi-J** [comment] 2021-11-30 08:13
Closing the issue.

**Closed by Shilpi-J** 2021-11-30 08:13 UTC
